// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwek9MgZ2ygsbBAkGm8TdnYDfsXMqXzlY',
    appId: '1:451218686097:web:ffe5004cf51d9f0a903f30',
    messagingSenderId: '451218686097',
    projectId: 'mygymapp-6238a',
    authDomain: 'mygymapp-6238a.firebaseapp.com',
    databaseURL: 'https://mygymapp-6238a-default-rtdb.firebaseio.com',
    storageBucket: 'mygymapp-6238a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD56jMJYbokx-rzz7NaOHddfF2DzlFN0I4',
    appId: '1:451218686097:android:758959d01b0cf077903f30',
    messagingSenderId: '451218686097',
    projectId: 'mygymapp-6238a',
    databaseURL: 'https://mygymapp-6238a-default-rtdb.firebaseio.com',
    storageBucket: 'mygymapp-6238a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGnVAogrO5T3K-IawuqMcQ4ihqNHG5Juk',
    appId: '1:451218686097:ios:1a6bb1fc8d8f4115903f30',
    messagingSenderId: '451218686097',
    projectId: 'mygymapp-6238a',
    databaseURL: 'https://mygymapp-6238a-default-rtdb.firebaseio.com',
    storageBucket: 'mygymapp-6238a.appspot.com',
    iosClientId: '451218686097-mha8ohj2m65lgfpln88h0ndvemig8d2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGnVAogrO5T3K-IawuqMcQ4ihqNHG5Juk',
    appId: '1:451218686097:ios:1a6bb1fc8d8f4115903f30',
    messagingSenderId: '451218686097',
    projectId: 'mygymapp-6238a',
    databaseURL: 'https://mygymapp-6238a-default-rtdb.firebaseio.com',
    storageBucket: 'mygymapp-6238a.appspot.com',
    iosClientId: '451218686097-mha8ohj2m65lgfpln88h0ndvemig8d2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
